### ISSUE TITLE
Riboreads fails on bioproject PRJNA396840, sample SRR5892185

### ISSUE THREAD

**Issue by simonleandergrimm** [naobservatory/mgs-pipeline#58]
Posting this for awareness. I didn't resolve this error and instead dropped the stage from my `run.py` run.

Error message:
```
riboreads: handling SRR5892185 inputs in /tmp/tmpw32tl8yy
download: s3://nao-mgs/PRJNA396840/cleaned/SRR5892185.collapsed.gz to ./SRR5892185.collapsed.gz
Calculating average read length...
Done. Average read length is  135
2024-01-07 17:07:09 : INFO  Using high MCC model
2024-01-07 17:07:09 : INFO  Log file: ribodetector.log
2024-01-07 17:07:09 : INFO  Classify reads with chunk size 512
2024-01-07 17:07:09 : INFO  Classify paired end reads with chunk size 512
2024-01-07 17:07:09 : INFO  Writing output non-rRNA sequences into file: SRR5892185.collapsed.nonrrna.fq
2024-01-07 17:08:03 : INFO  524288 reads classified!
2024-01-07 17:08:56 : INFO  1048576 reads classified!
2024-01-07 17:09:49 : INFO  1572864 reads classified!
2024-01-07 17:10:18 : INFO  1875901 reads classified!
2024-01-07 17:10:18 : INFO  Detected 1808789 non-rRNA sequences
2024-01-07 17:10:18 : INFO  Detected 67112 rRNA sequences
Number of rRNA reads in SRR5892185 = 74160/2577323 (3%)
riboreads: handling SRR5892185_output in /tmp/tmpd_dpvjll
Traceback (most recent call last):
  File "/home/ec2-user/code/mgs-pipeline/./run.py", line 1551, in <module>
    start()
  File "/home/ec2-user/code/mgs-pipeline/./run.py", line 1547, in start
    STAGE_FNS[stage](args)
  File "/home/ec2-user/code/mgs-pipeline/./run.py", line 635, in riboreads
    gzipped_file.write(title + "\n")
  File "/usr/lib64/python3.9/gzip.py", line 284, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str
```

**Comment by jeffkaufman** [comment]
Obsoleted by 4a05164
